//
// InlineObject5Model.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthAccountChangePasswordModel: Codable, Hashable {

    /** Password */
    public var password: String
    /** Current Password */
    public var currentPassword: String

    public init(password: String, currentPassword: String) {
        self.password = password
        self.currentPassword = currentPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case password
        case currentPassword = "current_password"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(password, forKey: .password)
        try container.encode(currentPassword, forKey: .currentPassword)
    }
}

