//
// InlineObject19Model.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelsGroupsCreateGroupModel: Codable, Hashable {

    /** Group name */
    public var name: String
    /** Group description */
    public var description: String?
    /** Nonce value, prefer to use ULIDs here for better feature support.  Used to prevent double requests to create objects. */
    public var nonce: String
    /** Array of user IDs to add to the group.  Must be friends with them. */
    public var users: [String]?
    /** Whether this group is not safe for work */
    public var nsfw: Bool?

    public init(name: String, description: String? = nil, nonce: String, users: [String]? = nil, nsfw: Bool? = nil) {
        self.name = name
        self.description = description
        self.nonce = nonce
        self.users = users
        self.nsfw = nsfw
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case nonce
        case users
        case nsfw
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(nonce, forKey: .nonce)
        try container.encodeIfPresent(users, forKey: .users)
        try container.encodeIfPresent(nsfw, forKey: .nsfw)
    }
}

