//
// InlineResponse2004IdModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerMemberIDResponseModel: Codable, Hashable {

    /** Id */
    public var server: String
    /** Id */
    public var user: String

    public init(server: String, user: String) {
        self.server = server
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case server
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(server, forKey: .server)
        try container.encode(user, forKey: .user)
    }
}

