//
// InlineResponse2002AttachmentsModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AttachmentModel: Codable, Hashable {
    
    /** Attachment ID */
    public var id: String
    
    public var tag: AttachmentTagModel
    /** File size (in bytes) */
    public var size: Double
    /** File name */
    public var filename: String
    /** Metadata */
    public var metadata: AttachmentMetadataModel
    /** Content type */
    public var contentType: String
    
    public init(id: String, tag: AttachmentTagModel, size: Double, filename: String, metadata: AttachmentMetadataModel, contentType: String) {
        self.id = id
        self.tag = tag
        self.size = size
        self.filename = filename
        self.metadata = metadata
        self.contentType = contentType
    }
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case tag
        case size
        case filename
        case metadata
        case contentType = "content_type"
    }
    
    // Encodable protocol methods
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tag, forKey: .tag)
        try container.encode(size, forKey: .size)
        try container.encode(filename, forKey: .filename)
        try container.encode(metadata, forKey: .metadata)
        try container.encode(contentType, forKey: .contentType)
    }
}

