//
// InlineObject6Model.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthAccountChangeEmailModel: Codable, Hashable {
    
    /** Current Password */
    public var currentPassword: String
    /** Valid email */
    public var email: String
    
    public init(currentPassword: String, email: String) {
        self.currentPassword = currentPassword
        self.email = email
    }
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currentPassword = "current_password"
        case email
    }
    
    // Encodable protocol methods
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currentPassword, forKey: .currentPassword)
        try container.encode(email, forKey: .email)
    }
}

