//
// InlineObject7Model.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthSessionLoginModel: Codable, Hashable {

    /** Valid email address */
    public var email: String
    /** Password */
    public var password: String?
    /** Security Key Challenge */
    public var challenge: String?
    /** Session Friendly Name */
    public var friendlyName: String?
    /** Captcha verification code */
    public var captcha: String?

    public init(email: String, password: String? = nil, challenge: String? = nil, friendlyName: String? = nil, captcha: String? = nil) {
        self.email = email
        self.password = password
        self.challenge = challenge
        self.friendlyName = friendlyName
        self.captcha = captcha
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case challenge
        case friendlyName = "friendly_name"
        case captcha
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(challenge, forKey: .challenge)
        try container.encodeIfPresent(friendlyName, forKey: .friendlyName)
        try container.encodeIfPresent(captcha, forKey: .captcha)
    }
}

