//
// InlineObject1Model.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuthAccountCreateAccountModel: Codable, Hashable {
    
    /** Valid email address */
    public var email: String
    /** Password */
    public var password: String
    /** Invite Code */
    public var invite: String?
    /** Captcha verification code */
    public var captcha: String?
    
    public init(email: String, password: String, invite: String? = nil, captcha: String? = nil) {
        self.email = email
        self.password = password
        self.invite = invite
        self.captcha = captcha
    }
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case invite
        case captcha
    }
    
    // Encodable protocol methods
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(invite, forKey: .invite)
        try container.encodeIfPresent(captcha, forKey: .captcha)
    }
}

