//
// ChannelsChannelMessagesRepliesModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChannelsChannelMessagesRepliesModel: Codable, Hashable {

    /** Message Id */
    public var id: String
    /** Whether this reply should mention the message's author. */
    public var mention: Bool

    public init(id: String, mention: Bool) {
        self.id = id
        self.mention = mention
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case mention
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(mention, forKey: .mention)
    }
}

