//
// InlineObject15Model.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MessageModel: Codable, Hashable {
    
    /** Message content to send. */
    public var content: String
    /** Nonce value, prefer to use ULIDs here for better feature support.  Used to prevent double requests to create objects. */
    public var nonce: String
    /** Attachments to include in message. */
    public var attachments: [AttachmentModel]?
    /** Messages to reply to. */
    public var replies: [ChannelsChannelMessagesRepliesModel]?
    
    public init(content: String, nonce: String, attachments: [AttachmentModel]? = nil, replies: [ChannelsChannelMessagesRepliesModel]? = nil) {
        self.content = content
        self.nonce = nonce
        self.attachments = attachments
        self.replies = replies
    }
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case nonce
        case attachments
        case replies
    }
    
    // Encodable protocol methods
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(content, forKey: .content)
        try container.encode(nonce, forKey: .nonce)
        try container.encodeIfPresent(attachments, forKey: .attachments)
        try container.encodeIfPresent(replies, forKey: .replies)
    }
}

