//
// ServersServerCategoriesModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServerCategoriesModel: Codable, Hashable {

    /** Id */
    public var id: String
    public var title: String
    public var channels: [String]

    public init(id: String, title: String, channels: [String]) {
        self.id = id
        self.title = title
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case channels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(channels, forKey: .channels)
    }
}

