//
// InlineObject22Model.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServersServerInformationCreateChannelModel: Codable, Hashable {
    
    public enum TypeModel: String, Codable, CaseIterable {
        case text = "Text"
        case voice = "Voice"
    }
    /** Channel type */
    public var type: TypeModel
    /** Channel name */
    public var name: String
    /** Channel description */
    public var description: String?
    /** Whether this channel is not safe for work */
    public var nsfw: Bool?
    /** Nonce value, prefer to use ULIDs here for better feature support.  Used to prevent double requests to create objects. */
    public var nonce: String
    
    public init(type: TypeModel, name: String, description: String? = nil, nsfw: Bool? = nil, nonce: String) {
        self.type = type
        self.name = name
        self.description = description
        self.nsfw = nsfw
        self.nonce = nonce
    }
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case name
        case description
        case nsfw
        case nonce
    }
    
    // Encodable protocol methods
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(nsfw, forKey: .nsfw)
        try container.encode(nonce, forKey: .nonce)
    }
}

